"""empty message

Revision ID: f8b611f75b43
Revises: 2cff70d95080
Create Date: 2025-08-10 19:37:03.495074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8b611f75b43'
down_revision = '2cff70d95080'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TodoList2', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TodoList2', schema=None) as batch_op:
        batch_op.drop_column('time')

    # ### end Alembic commands ###
